name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Backend Docker Job
  backend:
    name: Backend - Docker Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build Docker Image
        run: docker build -t backend-app:latest ./backend

  # Frontend Docker Job
  frontend:
    name: Frontend - Docker Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Docker Image
        run: docker build -t frontend-app:latest ./frontend

  # Deployment Job (optional)
  deploy:
    name: Deploy Containers
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Image
        run: |
          docker tag backend-app:latest <dockerhub-username>/backend-app:latest
          docker push <dockerhub-username>/backend-app:latest

      - name: Push Frontend Image
        run: |
          docker tag frontend-app:latest <dockerhub-username>/frontend-app:latest
          docker push <dockerhub-username>/frontend-app:latest
